version: '3.8'

services:
  dremio-adapter:
    build: .
    container_name: dremio-adapter
    ports:
      - "3002:3005"
    env_file: .env
    environment:
      - NODE_ENV=production
      - API_PORT=3005
    networks:
      - grafana-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3005/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana-net
    depends_on:
      dremio-adapter:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_LOG_LEVEL=debug

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana-storage:
